CREATE TABLE `bess_reports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`siteId` int NOT NULL,
	`reportType` enum('daily','weekly') NOT NULL,
	`periodStart` timestamp NOT NULL,
	`periodEnd` timestamp NOT NULL,
	`avgSoc` float NOT NULL,
	`minSoc` float NOT NULL,
	`maxSoc` float NOT NULL,
	`avgPvPower` float,
	`maxPvPower` float,
	`avgLoadPower` float,
	`maxLoadPower` float,
	`avgBatteryPower` float,
	`avgTemperature` float,
	`maxTemperature` float,
	`totalReadings` int NOT NULL DEFAULT 0,
	`loadOnMinutes` int NOT NULL DEFAULT 0,
	`estimatedEnergyKwh` float NOT NULL DEFAULT 0,
	`totalEvents` int NOT NULL DEFAULT 0,
	`totalAlarms` int NOT NULL DEFAULT 0,
	`maneuverCount` int NOT NULL DEFAULT 0,
	`notificationSent` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `bess_reports_id` PRIMARY KEY(`id`)
);
